export enum UserMessageCode {
  FORBIDDEN = "forbiden",
  USER_CREATED = "UserCreated",
  USER_UPDATED = "UserUpdated",
  USER_DELETED = "UserDeleted",
  INVALID_ROLE = "InvalidRole",
  UNAUTHORIZED = "Unauthorized",
  USER_RESTORED = "UserRestored",
  USER_NOT_FOUND = "UserNotFound",
  INVALID_STATUS = "InvalidStatus",
  INVALID_USER_ID = "InvalidUserId",
  USER_STATUS_UPDATED = "UserStatusUpdated",
  USER_ALREADY_EXISTS = "UserAlreadyExists",
  EMAIL_ALREADY_EXISTS = "EmailAlreadyExists",
  PHONE_ALREADY_EXISTS = "PhoneAlreadyExists",
  CANNOT_DELETE_ADMIN_USER = "CannotDeleteAdminUser",
  CANNOT_UPDATE_DELETED_USER = "CannotUpdatedDeletedUser",
}
