export enum CourseMessageCode {
  COURSE_CREATED = "COURSE_CREATED",
  COURSE_UPDATED = "COURSE_UPDATED",
  COURSE_DELETED = "COURSE_DELETED",
  COURSE_ARCHIVED = "COURSE_ARCHIVED",
  COURSE_RESTORED = "COURSE_RESTORED",
  COURSE_PUBLISHED = "COURSE_PUBLISHED",
  COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
  COURSE_SLUG_EXISTS = "COURSE_SLUG_EXISTS",
  COURSE_ACCESS_DENIED = "COURSE_ACCESS_DENIED",
  INVALID_COURSE_STATUS = "INVALID_COURSE_STATUS",
}
