import { type ExportLocale } from "@association/utils/association-report-export.util";

const EN = {
  "report.OVERVIEW_SUMMARY": "Overview summary",
  "report.MEMBER_PROGRESS": "Member progress",
  "report.GROUP_PROGRESS": "Group progress",
  "report.CATEGORY_COMPLETION": "Category completion",
  "report.MISSING_EVIDENCE": "Missing evidence",
  "report.RENEWAL_READINESS": "Renewal readiness",
  "answer.OVERVIEW_SUMMARY":
    "Where the membership stands overall, and how that moved against the previous period.",
  "answer.MEMBER_PROGRESS": "Who is ahead and who is behind, member by member.",
  "answer.GROUP_PROGRESS":
    "Which groups carry the membership and which lag behind.",
  "answer.CATEGORY_COMPLETION":
    "Which categories members complete and which they avoid.",
  "answer.MISSING_EVIDENCE":
    "Which members owe evidence before their credits can count.",
  "answer.RENEWAL_READINESS": "Who could renew today and who could not.",
  "band.RENEWAL_READY": "Renewal ready",
  "band.ON_TRACK": "On track",
  "band.AT_RISK": "At risk",
  "band.NOT_STARTED": "Not started",
  "period.THIS_YEAR": "This year",
  "period.LAST_YEAR": "Last year",
  "period.LAST_30_DAYS": "Last 30 days",
  "period.LAST_90_DAYS": "Last 90 days",
  "period.CUSTOM": "Custom range",
  "column.member": "Member",
  "column.email": "Email",
  "column.memberNumber": "Member number",
  "column.group": "Group",
  "column.band": "Band",
  "column.completion": "Completion",
  "column.requiredCredits": "Required credits",
  "column.completedCredits": "Credits earned",
  "column.awaiting": "Awaiting review",
  "column.deadline": "Earliest deadline",
  "column.requirement": "Requirement",
  "column.dueDate": "Due date",
  "column.daysRemaining": "Days remaining",
  "column.category": "Category",
  "column.mappedCategory": "Counts as",
  "column.averageEarned": "Average earned",
  "column.averageCompletion": "Average completion",
  "column.belowHalf": "Below half",
  "column.behind": "Behind",
  "column.members": "Members",
  "column.missingEvidence": "Missing evidence",
  "column.notStarted": "Not started",
  "column.neverStarted": "Never started",
  "column.renewalReady": "Renewal ready",
  "column.onTrack": "On track",
  "column.atRisk": "At risk",
  "column.readiness": "Renewal",
  "column.share": "Share",
  "column.change": "Change",
  "value.ready": "Ready",
  "value.notReady": "Not ready",
  "value.yes": "Yes",
  "value.no": "No",
  "value.none": "-",
  "summary.totalMembers": "Members",
  "summary.renewalReady": "Renewal ready",
  "summary.onTrack": "On track",
  "summary.atRisk": "At risk",
  "summary.missingEvidence": "Missing evidence",
  "summary.averageCompletion": "Average completion",
  "summary.period": "Period",
  "summary.computedAt": "Figures computed",
  "filter.period": "Period",
  "filter.group": "Group",
  "filter.requirement": "Requirement",
  "filter.includeInactive": "Includes inactive members",
  "filter.allGroups": "All groups",
  "filter.allRequirements": "All requirements",
  "document.generatedAt": "Generated",
  "document.rows": "Rows",
  "document.filter": "Filter",
  "document.summary": "Summary",
  "document.page": "Page {{page}} of {{pages}}",
  "document.truncated":
    "This export covers the first {{rows}} rows of {{total}}. Narrow the filter for the rest.",
  "document.empty": "No rows match this filter.",
  "document.platform": "Loopskey",
  "document.association": "Association",
  "sheet.report": "Report",
  "sheet.filter": "Filter",
} as const;

type LabelKey = keyof typeof EN;

const FR: Record<LabelKey, string> = {
  "report.OVERVIEW_SUMMARY": "Synthèse générale",
  "report.MEMBER_PROGRESS": "Progression des membres",
  "report.GROUP_PROGRESS": "Progression des groupes",
  "report.CATEGORY_COMPLETION": "Progression par catégorie",
  "report.MISSING_EVIDENCE": "Preuves manquantes",
  "report.RENEWAL_READINESS": "Prêts au renouvellement",
  "answer.OVERVIEW_SUMMARY":
    "Où en sont vos membres dans l'ensemble, et comment cela a évolué par rapport à la période précédente.",
  "answer.MEMBER_PROGRESS":
    "Qui est en avance et qui est en retard, membre par membre.",
  "answer.GROUP_PROGRESS":
    "Quels groupes portent l'association et lesquels sont en retard.",
  "answer.CATEGORY_COMPLETION":
    "Quelles catégories les membres complètent et lesquelles ils évitent.",
  "answer.MISSING_EVIDENCE":
    "Quels membres doivent fournir une preuve avant que leurs crédits comptent.",
  "answer.RENEWAL_READINESS":
    "Qui pourrait renouveler aujourd'hui et qui ne pourrait pas.",
  "band.RENEWAL_READY": "Prêt au renouvellement",
  "band.ON_TRACK": "En bonne voie",
  "band.AT_RISK": "À risque",
  "band.NOT_STARTED": "Pas commencé",
  "period.THIS_YEAR": "Cette année",
  "period.LAST_YEAR": "L'année dernière",
  "period.LAST_30_DAYS": "30 derniers jours",
  "period.LAST_90_DAYS": "90 derniers jours",
  "period.CUSTOM": "Période personnalisée",
  "column.member": "Membre",
  "column.email": "Courriel",
  "column.memberNumber": "Numéro de membre",
  "column.group": "Groupe",
  "column.band": "Statut",
  "column.completion": "Progression",
  "column.requiredCredits": "Crédits requis",
  "column.completedCredits": "Crédits obtenus",
  "column.awaiting": "En attente de revue",
  "column.deadline": "Échéance la plus proche",
  "column.requirement": "Exigence",
  "column.dueDate": "Date d'échéance",
  "column.daysRemaining": "Jours restants",
  "column.category": "Catégorie",
  "column.mappedCategory": "Comptée comme",
  "column.averageEarned": "Moyenne obtenue",
  "column.averageCompletion": "Progression moyenne",
  "column.belowHalf": "Sous la moitié",
  "column.behind": "En retard",
  "column.members": "Membres",
  "column.missingEvidence": "Preuves manquantes",
  "column.notStarted": "Pas commencé",
  "column.neverStarted": "Jamais commencé",
  "column.renewalReady": "Prêts au renouvellement",
  "column.onTrack": "En bonne voie",
  "column.atRisk": "À risque",
  "column.readiness": "Renouvellement",
  "column.share": "Part",
  "column.change": "Évolution",
  "value.ready": "Prêt",
  "value.notReady": "Pas prêt",
  "value.yes": "Oui",
  "value.no": "Non",
  "value.none": "-",
  "summary.totalMembers": "Membres",
  "summary.renewalReady": "Prêts au renouvellement",
  "summary.onTrack": "En bonne voie",
  "summary.atRisk": "À risque",
  "summary.missingEvidence": "Preuves manquantes",
  "summary.averageCompletion": "Progression moyenne",
  "summary.period": "Période",
  "summary.computedAt": "Chiffres calculés le",
  "filter.period": "Période",
  "filter.group": "Groupe",
  "filter.requirement": "Exigence",
  "filter.includeInactive": "Inclut les membres inactifs",
  "filter.allGroups": "Tous les groupes",
  "filter.allRequirements": "Toutes les exigences",
  "document.generatedAt": "Généré le",
  "document.rows": "Lignes",
  "document.filter": "Filtre",
  "document.summary": "Synthèse",
  "document.page": "Page {{page}} sur {{pages}}",
  "document.truncated":
    "Cet export couvre les {{rows}} premières lignes sur {{total}}. Affinez le filtre pour le reste.",
  "document.empty": "Aucune ligne ne correspond à ce filtre.",
  "document.platform": "Loopskey",
  "document.association": "Association",
  "sheet.report": "Rapport",
  "sheet.filter": "Filtre",
};

const DICTIONARIES: Record<ExportLocale, Record<LabelKey, string>> = {
  en: EN,
  fr: FR,
};

export type ExportTranslator = (
  key: LabelKey,
  vars?: Record<string, string | number>,
) => string;

export const exportTranslator = (locale: ExportLocale): ExportTranslator => {
  const dictionary = DICTIONARIES[locale];

  return (key, vars) => {
    const text = dictionary[key];
    if (!vars) return text;
    return Object.entries(vars).reduce(
      (result, [name, value]) =>
        result.split(`{{${name}}}`).join(String(value)),
      text,
    );
  };
};
