export enum PodcastMessageCode {
  PODCAST_CREATED = "PODCAST_CREATED",
  PODCAST_UPDATED = "PODCAST_UPDATED",
  PODCAST_DELETED = "PODCAST_DELETED",
  PODCAST_RESTORED = "PODCAST_RESTORED",
  PODCAST_ARCHIVED = "PODCAST_ARCHIVED",
  PODCAST_PUBLISHED = "PODCAST_PUBLISHED",
  PODCAST_NOT_FOUND = "PODCAST_NOT_FOUND",
  PODCAST_ACCESS_DENIED = "PODCAST_ACCESS_DENIED",
  PODCAST_EPISODE_CREATED = "PODCAST_EPISODE_CREATED",
  PODCAST_EPISODE_UPDATED = "PODCAST_EPISODE_UPDATED",
  PODCAST_EPISODE_DELETED = "PODCAST_EPISODE_DELETED",
  PODCAST_EPISODE_NOT_FOUND = "PODCAST_EPISODE_NOT_FOUND",
}
