ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ORGANIZATION_ACCOUNT_ACTIVATED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ORGANIZATION_ACTIVATION_RESENT';

ALTER TABLE "User"
ADD COLUMN "passwordChangedAt" TIMESTAMP(3);
