export enum CourseMessageCode {
  COURSE_CREATED = "COURSE_CREATED",
  COURSE_UPDATED = "COURSE_UPDATED",
  COURSE_DELETED = "COURSE_DELETED",
  COURSE_ARCHIVED = "COURSE_ARCHIVED",
  COURSE_RESTORED = "COURSE_RESTORED",
  COURSE_PUBLISHED = "COURSE_PUBLISHED",
  COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
  COURSE_SLUG_EXISTS = "COURSE_SLUG_EXISTS",
  COURSE_ACCESS_DENIED = "COURSE_ACCESS_DENIED",
  INVALID_COURSE_STATUS = "INVALID_COURSE_STATUS",
}

export enum EventMessageCode {
  EVENT_CREATED = "EVENT_CREATED",
  EVENT_UPDATED = "EVENT_UPDATED",
  EVENT_DELETED = "EVENT_DELETED",
  EVENT_RESTORED = "EVENT_RESTORED",
  EVENT_ARCHIVED = "EVENT_ARCHIVED",
  EVENT_CANCELLED = "EVENT_CANCELLED",
  EVENT_PUBLISHED = "EVENT_PUBLISHED",
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  EVENT_ACCESS_DENIED = "EVENT_ACCESS_DENIED",
  EVENT_CAPACITY_REACHED = "EVENT_CAPACITY_REACHED",
  EVENT_ALREADY_REGISTERED = "EVENT_ALREADY_REGISTERED",
  EVENT_REGISTRATION_DISABLED = "EVENT_REGISTRATION_DISABLED",
  EVENT_REGISTRATION_NOT_FOUND = "EVENT_REGISTRATION_NOT_FOUND",
}

export enum PodcastMessageCode {
  PODCAST_CREATED = "PODCAST_CREATED",
  PODCAST_UPDATED = "PODCAST_UPDATED",
  PODCAST_DELETED = "PODCAST_DELETED",
  PODCAST_RESTORED = "PODCAST_RESTORED",
  PODCAST_ARCHIVED = "PODCAST_ARCHIVED",
  PODCAST_PUBLISHED = "PODCAST_PUBLISHED",
  PODCAST_NOT_FOUND = "PODCAST_NOT_FOUND",
  PODCAST_ACCESS_DENIED = "PODCAST_ACCESS_DENIED",
  PODCAST_EPISODE_CREATED = "PODCAST_EPISODE_CREATED",
  PODCAST_EPISODE_UPDATED = "PODCAST_EPISODE_UPDATED",
  PODCAST_EPISODE_DELETED = "PODCAST_EPISODE_DELETED",
  PODCAST_EPISODE_NOT_FOUND = "PODCAST_EPISODE_NOT_FOUND",
}

export enum YouTubeMessageCode {
  YOUTUBE_VIDEO_CREATED = "YOUTUBE_VIDEO_CREATED",
  YOUTUBE_VIDEO_DELETED = "YOUTUBE_VIDEO_DELETED",
  YOUTUBE_VIDEO_UPDATED = "YOUTUBE_VIDEO_UPDATED",
  YOUTUBE_VIDEO_NOT_FOUND = "YOUTUBE_VIDEO_NOT_FOUND",
  YOUTUBE_CHANNEL_CREATED = "YOUTUBE_CHANNEL_CREATED",
  YOUTUBE_CHANNEL_DELETED = "YOUTUBE_CHANNEL_DELETED",
  YOUTUBE_CHANNEL_UPDATED = "YOUTUBE_CHANNEL_UPDATED",
  YOUTUBE_CHANNEL_RESTORED = "YOUTUBE_CHANNEL_RESTORED",
  YOUTUBE_CHANNEL_ARCHIVED = "YOUTUBE_CHANNEL_ARCHIVED",
  YOUTUBE_CHANNEL_PUBLISHED = "YOUTUBE_CHANNEL_PUBLISHED",
  YOUTUBE_CHANNEL_NOT_FOUND = "YOUTUBE_CHANNEL_NOT_FOUND",
  YOUTUBE_CHANNEL_ACCESS_DENIED = "YOUTUBE_CHANNEL_ACCESS_DENIED",
}

export enum ProviderMessageCode {
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  PROVIDER_EVENTS_FETCHED = "PROVIDER_EVENTS_FETCHED",
  PROVIDER_ACCESS_REQUIRED = "PROVIDER_ACCESS_REQUIRED",
  PROVIDER_SETTINGS_FETCHED = "PROVIDER_SETTINGS_FETCHED",
  PROVIDER_SETTINGS_UPDATED = "PROVIDER_SETTINGS_UPDATED",
  PROVIDER_OVERVIEW_FETCHED = "PROVIDER_OVERVIEW_FETCHED",
  PROVIDER_ANALYTICS_FETCHED = "PROVIDER_ANALYTICS_FETCHED",
  PROVIDER_ATTENDEES_FETCHED = "PROVIDER_ATTENDEES_FETCHED",
  PROMOTION_REQUEST_SUBMITTED = "PROMOTION_REQUEST_SUBMITTED",
  PROVIDER_ANALYTICS_CSV_EXPORTED = "PROVIDER_ANALYTICS_CSV_EXPORTED",
  PROVIDER_PROMOTION_REQUESTS_FETCHED = "PROVIDER_PROMOTION_REQUESTS_FETCHED",
  PROMOTION_ALREADY_REQUEST = "This event already has an active promotion request.",
}

export enum ExtMessageCodeError {
  INVALID_EXTERNAL_LEARNING_INPUT = "InvalidExternalLearningInput",
  EXTERNAL_LEARNING_ACTIVITY_NOT_FOUND = "ExternalLearningActivityNotFound",
}
