export enum IngestionMessageCode {
  INGESTION_UNAUTHORIZED = "INGESTION_UNAUTHORIZED",
  INGESTION_RATE_LIMITED = "INGESTION_RATE_LIMITED",
  INGESTION_SOURCE_INACTIVE = "INGESTION_SOURCE_INACTIVE",
  INGESTION_SOURCE_NOT_CALLER_SUPPLIED = "INGESTION_SOURCE_NOT_CALLER_SUPPLIED",
}
