export enum IngestionMessageCode {
  INGESTION_UNAUTHORIZED = "INGESTION_UNAUTHORIZED",
  INGESTION_RATE_LIMITED = "INGESTION_RATE_LIMITED",
  INGESTION_SOURCE_INACTIVE = "INGESTION_SOURCE_INACTIVE",
  INGESTION_SOURCE_NOT_CALLER_SUPPLIED = "INGESTION_SOURCE_NOT_CALLER_SUPPLIED",
  INGESTION_CONTRACT_VERSION_UNSUPPORTED = "INGESTION_CONTRACT_VERSION_UNSUPPORTED",
  INGESTION_KIND_MISMATCH = "INGESTION_KIND_MISMATCH",
  INGESTION_ENVELOPE_INVALID = "INGESTION_ENVELOPE_INVALID",
  INGESTION_FIELD_MAP_INVALID = "INGESTION_FIELD_MAP_INVALID",
  INGESTION_IDEMPOTENCY_KEY_REQUIRED = "INGESTION_IDEMPOTENCY_KEY_REQUIRED",
  INGESTION_BATCH_TOO_LARGE = "INGESTION_BATCH_TOO_LARGE",
  INGESTION_BODY_TOO_LARGE = "INGESTION_BODY_TOO_LARGE",
  INGESTION_BATCH_NOT_FOUND = "INGESTION_BATCH_NOT_FOUND",
}
