export enum ContactInquiryMessageCode {
  CONTACT_INQUIRY_INVALID = "CONTACT_INQUIRY_INVALID",
  CONTACT_INQUIRY_SUBMITTED = "CONTACT_INQUIRY_SUBMITTED",
  CONTACT_INQUIRY_RATE_LIMITED = "CONTACT_INQUIRY_RATE_LIMITED",
  CONTACT_INQUIRY_DELIVERY_FAILED = "CONTACT_INQUIRY_DELIVERY_FAILED",
}
