export enum AdminDashboardMessageCode {
  ADMIN_ONLY = "AminOnly",
  USER_NOT_FOUND = "UserNotFound",
  PROFILE_UPDATED = "ProfileUpdated",
  USER_STATUS_UPDATED = "UserStatusUpdated",
  USER_ALREADY_EXISTS = "UserAlreadyExists",
  USER_ROLE_CONFLICT = "UserRoleConflict",
  ORGANIZATION_NOT_FOUND = "OrganizationNotFound",
  ORGANIZATION_ALREADY_EXISTS = "OrganizationAlreadyExists",
  ORG_ACCESS_REQUEST_APPROVED = "OrgAccessRequestApproved",
  ORG_ACCESS_REQUEST_REJECTED = "OrgAccessRequestRejected",
  ORGANIZATION_MEMBER_REMOVED = "OrganizationMemberRemoved",
  ORG_ACCESS_REQUEST_NOT_FOUND = "OrgAccessRequestNotFound",
  ORG_ACCESS_REQUEST_INVALID = "OrgAccessRequestInvalid",
  ORG_ACCESS_REQUEST_ALREADY_REVIEWED = "OrgAccessRequestAlreadyReviewed",
  ORGANIZATION_MEMBER_NOT_FOUND = "OrganizationMemberNotFound",
  ORGANIZATION_SETTINGS_UPDATED = "OrganizationSettingsUpdated",
}
