export enum ProfessionalGqlObjectNames {
  PAGE_INFO = "ProfessionalPageInfo",
  PROFESSIONAL_COURSE = "ProfessionalCourse",
  PROFESSIONAL_SESSION = "ProfessionalSession",
  PROFESSIONAL_ROADMAP = "ProfessionalRoadmap",
  PROFESSIONAL_PAYMENT = "ProfessionalPayment",
  PROFESSIONAL_OVERVIEW = "ProfessionalOverview",
  PROFESSIONAL_SETTINGS = "ProfessionalSettings",
  PROFESSIONAL_PDU_REPORT = "ProfessionalPduReport",
  PROFESSIONAL_PDU_TARGET = "ProfessionalPduTarget",
  PROFESSIONAL_COURSE_INFO = "ProfessionalCourseInfo",
  PROFESSIONAL_CERTIFICATE = "ProfessionalCertificate",
  PROFESSIONAL_PDU_ACTIVITY = "ProfessionalPduActivity",
  PROFESSIONAL_ROADMAP_STEP = "ProfessionalRoadmapStep",
  PROFESSIONAL_ROADMAP_PHASE = "ProfessionalRoadmapPhase",
  PROFESSIONAL_CALENDAR_EVENT = "ProfessionalCalendarEvent",
  PROFESSIONAL_ACTION_RESPONSE = "ProfessionalActionResponse",
  PROFESSIONAL_EXPLORE_ROADMAP = "ProfessionalExploreRoadmap",
  PROFESSIONAL_PAYMENT_OVERVIEW = "ProfessionalPaymentOverview",
  PROFESSIONAL_DASHBOARD_PROFILE = "ProfessionalDashboardProfile",
  PAGINATED_PROFESSIONAL_COURSES = "PaginatedProfessionalCourses",
  PAGINATED_PROFESSIONAL_PAYMENTS = "PaginatedProfessionalPayments",
  PAGINATED_PROFESSIONAL_ROADMAPS = "PaginatedProfessionalRoadmaps",
  PROFESSIONAL_CALENDAR_Event_INFO = "ProfessionalCalendarEventInfo",
  PROFESSIONAL_PDU_MONTHLY_POINT = "ProfessionalPduMonthlyPoint",
  PROFESSIONAL_PDU_ACTIVITY_FILE = "ProfessionalPduActivityFile",
  PROFESSIONAL_PDU_CATEGORY_SUMMARY = "ProfessionalPduCategorySummary",
  PROFESSIONAL_CERTIFICATE_OVERVIEW = "ProfessionalCertificateOverview",
  PROFESSIONAL_MANUAL_CALENDAR_EVENT = "ProfessionalManualCalendarEvent",
  PAGINATED_PROFESSIONAL_CERTIFICATES = "PaginatedProfessionalCertificates",
  PAGINATED_PROFESSIONAL_PDU_ACTIVITIES = "PaginatedProfessionalPduActivities",
  PAGINATED_PROFESSIONAL_CALENDAR_EVENTS = "PaginatedProfessionalCalendarEvents",
  PAGINATED_PROFESSIONAL_EXPLORE_ROADMAPS = "PaginatedProfessionalExploreRoadmaps",
}

export enum ProfessionalGqlInputNames {
  UPSERT_PDU_TARGET_INPUT = "UpsertPduTargetInput",
  CREATE_PDU_ACTIVITY_INPUT = "CreatePduActivityInput",
  UPDATE_PDU_ACTIVITY_INPUT = "UpdatePduActivityInput",
  PROFESSIONAL_SEARCH_INPUT = "ProfessionalSearchInput",
  PROFESSIONAL_PDU_ACTIVITY_FILTER_INPUT = "ProfessionalPduActivityFilterInput",
  CREATE_CALENDAR_EVENT_INPUT = "CreateCalendarEventInput",
  PROFESSIONAL_PAGINATION_INPUT = "ProfessionalPaginationInput",
  UPDATE_PROFESSIONAL_PROFILE_INPUT = "UpdateProfessionalProfileInput",
  CHANGE_PROFESSIONAL_PASSWORD_INPUT = "ChangeProfessionalPasswordInput",
  UPDATE_PROFESSIONAL_SETTINGS_INPUT = "UpdateProfessionalSettingsInput",
  PROFESSIONAL_CALENDAR_EVENTS_FILTER_INPUT = "ProfessionalCalendarEventsFilterInput",
}

export enum ProfessionalGqlQueryNames {
  MY_CALENDAR_ENTRIES = "myCalendarEntries",
  PROFESSIONAL_OVERVIEW = "professionalOverview",
  PROFESSIONAL_SETTINGS = "professionalSettings",
  PROFESSIONAL_PAYMENTS = "professionalPayments",
  PROFESSIONAL_PDU_REPORT = "professionalPduReport",
  PROFESSIONAL_MY_COURSES = "professionalMyCourses",
  PROFESSIONAL_MY_ROADMAPS = "professionalMyRoadmaps",
  PROFESSIONAL_CERTIFICATES = "professionalCertificates",
  PROFESSIONAL_PDU_ACTIVITY = "professionalPduActivity",
  PROFESSIONAL_PDU_ACTIVITIES = "professionalPduActivities",
  PROFESSIONAL_CONTENT_COMPLETION = "professionalContentCompletion",
  UPDATE_PROFESSIONAL_SETTINGS = "UpdateProfessionalSettings",
  PROFESSIONAL_ACTIVE_SESSIONS = "professionalActiveSessions",
  PROFESSIONAL_CALENDAR_EVENTS = "professionalCalendarEvents",
  PROFESSIONAL_EXPLORE_ROADMAPS = "professionalExploreRoadmaps",
  PROFESSIONAL_DASHBOARD_PROFILE = "professionalDashboardProfile",
}

export enum ProfessionalGqlMutationNames {
  CREATE_CALENDAR_EVENT = "createCalendarEvent",
  DELETE_CALENDAR_EVENT = "deleteCalendarEvent",
  RESET_PROFESSIONAL_SETTINGS = "resetProfessionalSettings",
  UPDATE_PROFESSIONAL_SETTINGS = "updateProfessionalSettings",
  UPSERT_PROFESSIONAL_PDU_TARGET = "upsertProfessionalPduTarget",
  CREATE_PROFESSIONAL_PDU_ACTIVITY = "createProfessionalPduActivity",
  UPDATE_PROFESSIONAL_PDU_ACTIVITY = "updateProfessionalPduActivity",
  DELETE_PROFESSIONAL_PDU_ACTIVITY = "deleteProfessionalPduActivity",
  UPDATE_PROFESSIONAL_DASHBOARD_PROFILE = "updateProfessionalDashboardProfile",
}
