export enum ProfessionalMessageCode {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  SETTINGS_RESET = "SETTINGS_RESET",
  PROFILE_FETCHED = "PROFILE_FETCHED",
  PROFILE_UPDATED = "PROFILE_UPDATED",
  SETTINGS_FETCHED = "SETTINGS_FETCHED",
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  PDU_TARGET_UPSERTED = "PDU_TARGET_UPSERTED",
  PDU_ACTIVITY_CREATED = "PDU_ACTIVITY_CREATED",
  PDU_ACTIVITY_UPDATED = "PDU_ACTIVITY_UPDATED",
  PDU_ACTIVITY_NOT_FOUND = "PDU_ACTIVITY_NOT_FOUND",
  PROFESSIONAL_ACCESS_REQUIRED = "PROFESSIONAL_ACCESS_REQUIRED",
}
