export enum ProfileSectionKey {
  PREFERENCES = "PREFERENCES",
  BASIC_PROFILE = "BASIC_PROFILE",
  CERTIFICATIONS = "CERTIFICATIONS",
  SKILLS_INTERESTS = "SKILLS_INTERESTS",
  PROFESSIONAL_DETAILS = "PROFESSIONAL_DETAILS",
}

export const PROFILE_SECTION_KEYS = [
  ProfileSectionKey.PREFERENCES,
  ProfileSectionKey.BASIC_PROFILE,
  ProfileSectionKey.CERTIFICATIONS,
  ProfileSectionKey.SKILLS_INTERESTS,
  ProfileSectionKey.PROFESSIONAL_DETAILS,
] as const;

export const PROFILE_TOTAL_SECTIONS = PROFILE_SECTION_KEYS.length;

export const PROFESSIONAL_SUMMARY_MAX_LENGTH = 1000;
export const LICENCE_NUMBER_MAX_LENGTH = 100;
