export enum ProfileSectionKey {
  PREFERENCES = "PREFERENCES",
  BASIC_PROFILE = "BASIC_PROFILE",
  CERTIFICATIONS = "CERTIFICATIONS",
  SKILLS_INTERESTS = "SKILLS_INTERESTS",
  PROFESSIONAL_DETAILS = "PROFESSIONAL_DETAILS",
}

export const PROFILE_SECTION_KEYS = [
  ProfileSectionKey.PREFERENCES,
  ProfileSectionKey.BASIC_PROFILE,
  ProfileSectionKey.CERTIFICATIONS,
  ProfileSectionKey.SKILLS_INTERESTS,
  ProfileSectionKey.PROFESSIONAL_DETAILS,
] as const;

export const PROFILE_TOTAL_SECTIONS = PROFILE_SECTION_KEYS.length;

export const PROFESSIONAL_SUMMARY_MAX_LENGTH = 1000;
export const LICENCE_NUMBER_MAX_LENGTH = 100;

export const ONBOARDING_MAX_SKILLS = 3;

export const CURRENT_ROLE_MAX_LENGTH = 120;

export const TAXONOMY_PAGE_DEFAULT = 20;

export const TAXONOMY_PAGE_MAX = 50;

export const TAXONOMY_SEARCH_MIN_LENGTH = 2;

export const TAXONOMY_SEARCH_MAX_LENGTH = 80;

export const TAXONOMY_HYDRATE_MAX = 50;

export const SKILL_SUGGESTION_LIMIT = 8;
