import { NeatConfig } from "@firecms/neat";

const NEAT_COLORS = {
  indigoDeep: "#130437",
  orchid: "#B34BD0",
  indigo: "#210751",
  violet: "#3511A5",
  mauve: "#8F3E8D",
  blush: "#FF9A9E",
} as const;

export const NEAT_GRADIENT_CONFIG: NeatConfig = {
  colors: [
    { color: NEAT_COLORS.indigoDeep, enabled: true },
    { color: NEAT_COLORS.orchid, enabled: true },
    { color: NEAT_COLORS.indigo, enabled: true },
    { color: NEAT_COLORS.violet, enabled: true },
    { color: NEAT_COLORS.mauve, enabled: false },
    { color: NEAT_COLORS.blush, enabled: false },
  ],
  speed: 4,
  // Pressure is swapped against the source preset so the bands run along Y.
  horizontalPressure: 3,
  verticalPressure: 7,
  waveFrequencyX: 0,
  waveFrequencyY: 0,
  waveAmplitude: 0,
  shadows: 4,
  highlights: 0,
  colorBrightness: 1.95,
  colorSaturation: 2,
  wireframe: false,
  colorBlending: 9,
  backgroundColor: NEAT_COLORS.indigo,
  backgroundAlpha: 1,
  grainScale: 6,
  grainSparsity: 0,
  grainIntensity: 0.125,
  grainSpeed: 0,
  resolution: 1.15,
  yOffset: 0.20001220703125,
  yOffsetWaveMultiplier: 4.5,
  yOffsetColorMultiplier: 4.8,
  yOffsetFlowMultiplier: 5.2,
  flowDistortionA: 0.4,
  flowDistortionB: 10,
  flowScale: 3.3,
  flowEase: 0.37,
  flowEnabled: true,
  enableProceduralTexture: false,
  transparentTextureVoid: false,
  textureVoidLikelihood: 0.06,
  textureVoidWidthMin: 10,
  textureVoidWidthMax: 500,
  textureBandDensity: 0.8,
  textureColorBlending: 0.06,
  textureSeed: 333,
  textureEase: 0.38,
  proceduralBackgroundColor: "#003FFF",
  textureShapeTriangles: 20,
  textureShapeCircles: 15,
  textureShapeBars: 15,
  textureShapeSquiggles: 10,
  domainWarpEnabled: false,
  domainWarpIntensity: 0,
  domainWarpScale: 3,
  vignetteIntensity: 0,
  vignetteRadius: 0.8,
  fresnelEnabled: false,
  fresnelPower: 2,
  fresnelIntensity: 0.5,
  fresnelColor: "#FFFFFF",
  iridescenceEnabled: false,
  iridescenceIntensity: 0.5,
  iridescenceSpeed: 1,
  bloomIntensity: 0,
  bloomThreshold: 0.7,
  chromaticAberration: 0,
  shapeType: "ribbon",
  shapeRotationX: 0,
  shapeRotationY: 0,
  shapeRotationZ: 0,
  shapeAutoRotateSpeedX: 0,
  shapeAutoRotateSpeedY: 0,
  sphereRadius: 15,
  torusRadius: 15,
  torusTube: 5,
  cylinderRadius: 10,
  cylinderHeight: 40,
  planeBend: 1.7,
  planeTwist: 5,
  silhouetteFade: 0.2,
  cylinderFade: 0.08,
  ribbonFade: 0.23,
  flatShading: false,
  cameraLock: false,
  cameraX: 15,
  cameraY: 0.5,
  cameraZ: 0,
  cameraRotationX: 0,
  cameraRotationY: 0,
  cameraRotationZ: 0,
  cameraZoom: 1.45,
};
