export const CANONICAL_STATIC_PAGE_PATHS = [
  "/",
  "/about",
  "/services",
  "/content",
  "/contact",
  "/faq",
  "/solutions/professionals",
  "/solutions/organizations",
  "/solutions/associations",
  "/solutions/content-providers",
  "/company/association-partners",
  "/company/content-providers",
  "/support/accessibility",
  "/support/security-data-protection",
  "/terms",
  "/privacy-policy",
  "/cookies",
] as const;
