export enum ProviderMessageCode {
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  PROVIDER_EVENTS_FETCHED = "PROVIDER_EVENTS_FETCHED",
  PROVIDER_ACCESS_REQUIRED = "PROVIDER_ACCESS_REQUIRED",
  PROVIDER_SETTINGS_FETCHED = "PROVIDER_SETTINGS_FETCHED",
  PROVIDER_SETTINGS_UPDATED = "PROVIDER_SETTINGS_UPDATED",
  PROVIDER_OVERVIEW_FETCHED = "PROVIDER_OVERVIEW_FETCHED",
  PROVIDER_ANALYTICS_FETCHED = "PROVIDER_ANALYTICS_FETCHED",
  PROVIDER_ATTENDEES_FETCHED = "PROVIDER_ATTENDEES_FETCHED",
  PROMOTION_REQUEST_SUBMITTED = "PROMOTION_REQUEST_SUBMITTED",
  PROVIDER_ANALYTICS_CSV_EXPORTED = "PROVIDER_ANALYTICS_CSV_EXPORTED",
  PROVIDER_PROMOTION_REQUESTS_FETCHED = "PROVIDER_PROMOTION_REQUESTS_FETCHED",
  PROMOTION_ALREADY_REQUEST = "This event already has an active promotion request.",
}
