export enum YouTubeMessageCode {
  YOUTUBE_VIDEO_CREATED = "YOUTUBE_VIDEO_CREATED",
  YOUTUBE_VIDEO_DELETED = "YOUTUBE_VIDEO_DELETED",
  YOUTUBE_VIDEO_UPDATED = "YOUTUBE_VIDEO_UPDATED",
  YOUTUBE_VIDEO_NOT_FOUND = "YOUTUBE_VIDEO_NOT_FOUND",
  YOUTUBE_CHANNEL_CREATED = "YOUTUBE_CHANNEL_CREATED",
  YOUTUBE_CHANNEL_DELETED = "YOUTUBE_CHANNEL_DELETED",
  YOUTUBE_CHANNEL_UPDATED = "YOUTUBE_CHANNEL_UPDATED",
  YOUTUBE_CHANNEL_RESTORED = "YOUTUBE_CHANNEL_RESTORED",
  YOUTUBE_CHANNEL_ARCHIVED = "YOUTUBE_CHANNEL_ARCHIVED",
  YOUTUBE_CHANNEL_PUBLISHED = "YOUTUBE_CHANNEL_PUBLISHED",
  YOUTUBE_CHANNEL_NOT_FOUND = "YOUTUBE_CHANNEL_NOT_FOUND",
  YOUTUBE_CHANNEL_ACCESS_DENIED = "YOUTUBE_CHANNEL_ACCESS_DENIED",
}
