export enum EventMessageCode {
  EVENT_CREATED = "EVENT_CREATED",
  EVENT_UPDATED = "EVENT_UPDATED",
  EVENT_DELETED = "EVENT_DELETED",
  EVENT_RESTORED = "EVENT_RESTORED",
  EVENT_ARCHIVED = "EVENT_ARCHIVED",
  EVENT_CANCELLED = "EVENT_CANCELLED",
  EVENT_PUBLISHED = "EVENT_PUBLISHED",

  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  EVENT_ACCESS_DENIED = "EVENT_ACCESS_DENIED",
  EVENT_CAPACITY_REACHED = "EVENT_CAPACITY_REACHED",
  EVENT_ALREADY_REGISTERED = "EVENT_ALREADY_REGISTERED",
  EVENT_REGISTRATION_DISABLED = "EVENT_REGISTRATION_DISABLED",
  EVENT_REGISTRATION_NOT_FOUND = "EVENT_REGISTRATION_NOT_FOUND",
}
