import { graphqlBaseQuery } from "@lib/rtk/graphqlBaseQuery";
import { createApi } from "@reduxjs/toolkit/query/react";

export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: graphqlBaseQuery(),
  tagTypes: [
    "Auth",
    "Cart",
    "User",
    "Users",
    "Admin",
    "Events",
    "Courses",
    "Reviews",
    "Podcasts",
    "Wishlist",
    "AdminUsers",
    "CurrentUser",
    "CurrentUser",
    "Enrollments",
    "Professional",
    "Organization",
    "AdminProfile",
    "Organization",
    "AdminOverview",
    "YouTubeVideos",
    "AdminAuditLogs",
    "ProviderEvents",
    "YouTubeChannels",
    "AdminUserGrowth",
    "PodcastEpisodes",
    "ProfessionalPdu",
    "ExternalLearning",
    "ProviderSettings",
    "ProviderOverview",
    "ProviderAnalytics",
    "ProviderAttendees",
    "PopularCategories",
    "ProviderPromotions",
    "EventRegistrations",
    "AdminOrganizations",
    "ContentInteraction",
    "ProfessionalCourses",
    "ProfessionalProfile",
    "OrganizationReports",
    "OrganizationMembers",
    "OrganizationMembers",
    "OrganizationReports",
    "ProfessionalRoadmaps",
    "OrganizationSettings",
    "OrganizationOverview",
    "ProfessionalOverview",
    "ProfessionalSettings",
    "ProfessionalSessions",
    "ProfessionalCalendar",
    "ProfessionalPayments",
    "ProviderAnalyticsCsv",
    "OrganizationOverview",
    "OrganizationSettings",
    "ProfessionalDashboard",
    "AdminOrganizationDetail",
    "AdminOrgAccessRequests",
    "OrganizationAssignments",
    "OrganizationAssignments",
    "OrganizationDepartments",
    "AdminOrganizationUsers",
    "OrganizationDepartments",
    "OrganizationEventCatalog",
    "OrganizationEventCatalog",
    "AdminOrganizationMembers",
    "ProfessionalCertificates",
    "OrganizationCpdCategories",
    "OrganizationCpdCategories",
    "OrganizationAccessRequest",
    "OrganizationAccessRequests",
  ],
  endpoints: () => ({}),
});
