export enum OrganizationAccessRequestMessageCode {
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_SUBMITTED = "REQUEST_SUBMITTED",
  REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_REVIEW_STATUS = "INVALID_REVIEW_STATUS",
  REQUEST_ALREADY_EXISTS = "REQUEST_ALREADY_EXISTS",
  REQUEST_ALREADY_REVIEWED = "REQUEST_ALREADY_REVIEWED",
}
