export enum OrganizationDashboardGqlObjectNames {
  PAGE_INFO = "OrganizationPageInfo",
  ORGANIZATION_REPORT = "OrganizationReport",
  ORGANIZATION_MEMBER = "OrganizationMember",
  ORGANIZATION_OVERVIEW = "OrganizationOverview",
  ORGANIZATION_SETTINGS = "OrganizationSettings",
  ORGANIZATION_DEPARTMENT = "OrganizationDepartment",
  ORGANIZATION_ASSIGNMENT = "OrganizationAssignment",
  ORGANIZATION_CPD_CATEGORY = "OrganizationCpdCategory",
  ORGANIZATION_MEMBERS_STATS = "OrganizationMembersStats",
  ORGANIZATION_MEMBERS_DETAIL = "OrganizationMemberDetail",
  ORGANIZATION_TRENDING_TOPIC = "OrganizationTrendingTopic",
  ORGANIZATION_REPORT_SUMMARY = "OrganizationReportSummary",
  ORGANIZATION_ACTION_RESPONSE = "OrganizationActionResponse",
  ORGANIZATION_ASSIGNMENT_STATS = "OrganizationAssignmentStats",
  ORGANIZATION_OVERVIEW_SUMMARY = "OrganizationOverviewSummary",
  ORGANIZATION_ATTENTION_MEMBER = "OrganizationAttentionMember",
  ORGANIZATION_REPORT_TOP_MEMBER = "OrganizationReportTopMember",
  PAGINATED_ORGANIZATION_MEMBERS = "PaginatedOrganizationMembers",
  ORGANIZATION_REPORT_DEPARTMENT = "OrganizationReportDepartment",
  ORGANIZATION_REPORT_TREND_POINT = "OrganizationReportTrendPoint",
  ORGANIZATION_CPD_CATEGORY_STATS = "OrganizationCpdCategoryStats",
  ORGANIZATION_EVENT_CATALOG_ITEM = "OrganizationEventCatalogItem",
  PAGINATED_ORGANIZATION_ASSIGNMENTS = "PaginatedOrganizationAssignments",
  BULIK_ADD_ORGANIZATION_MEMBER_RESULT = "BulkAddOrganizationMembersResult",
  PAGINATED_ORGANIZATION_EVENT_CATALOG = "PaginatedOrganizationEventCatalog",
  ORGANIZATION_COMPLIANCE_DISTRIBUTION = "OrganizationComplianceDistribution",
  PAGINATED_ORGANIZATION_CPD_CATEGORIES = "PaginatedOrganizationCpdCategories",
}

export enum OrganizationDashboardGqlInputNames {
  EVENT_CATALOG_FILTER_INPUT = "EventCatalogFilterInput",
  ADD_ORGANIZATION_MEMBER_INPUT = "AddOrganizationMemberInput",
  BULK_ORG_MEMBER_ROW_INPUT = "BulkOrganizationMemberRowInput",
  ORGANIZATION_PAGINATION_INPUT = "OrganizationPaginationInput",
  BULK_ADD_ORG_MEMBERS_INPUT = "BulkAddOrganizationMembersInput",
  UPDATE_ORGANIZATION_MEMBER_INPUT = "UpdateOrganizationMemberInput",
  ORGANIZATION_MEMBER_FILTER_INPUT = "OrganizationMemberFilterInput",
  ORGANIZATION_REPORT_FILTER_INPUT = "OrganizationReportFilterInput",
  UPDATE_ORGANIZATION_SETTINGS_INPUT = "UpdateOrganizationSettingsInput",
  CREATE_ORGANIZATION_DEPARTMENT_INPUT = "CreateOrganizationDepartmentInput",
  UPDATE_ORGANIZATION_DEPARTMENT_INPUT = "UpdateOrganizationDepartmentInput",
  ORGANIZATION_ASSIGNMENT_FILTER_INPUT = "OrganizationAssignmentFilterInput",
  CREATE_ORGANIZATION_ASSIGNMENT_INPUT = "CreateOrganizationAssignmentInput",
  ORGANIZATION_CPD_CATEGORY_FILTER_INPUT = "OrganizationCpdCategoryFilterInput",
  UPDATE_ORGANIZATION_MEMBER_NOTES_INPUT = "UpdateOrganizationMemberNotesInput",
  CREATE_ORGANIZATION_CPD_CATEGORY_INPUT = "CreateOrganizationCpdCategoryInput",
  UPDATE_ORGANIZATION_CPD_CATEGORY_INPUT = "UpdateOrganizationCpdCategoryInput",
  ORGANIZATION_REPORT_TOP_MEMBERS_INPUT = "OrganizationReportTopMembersFilterInput",
}

export enum OrganizationDashboardGqlQueryNames {
  REPORTS = "organizationReports",
  MEMBERS = "organizationMembers",
  OVERVIEW = "organizationOverview",
  SETTINGS = "organizationSettings",
  ASSIGNMENTS = "organizationAssignments",
  DEPARTMENTS = "organizationDepartments",
  EVENT_CATALOG = "organizationEventCatalog",
  CPD_CATEGORIES = "organizationCpdCategories",
}

export enum OrganizationDashboardGqlMutationNames {
  ADD_MEMBER = "addOrganizationMember",
  UPDATE_MEMBER = "updateOrganizationMember",
  UPDATE_SETTINGS = "updateOrganizationSettings",
  CREATE_DEPARTMENT = "createOrganizationDepartment",
  UPDATE_DEPARTMENT = "updateOrganizationDepartment",
  DELETE_DEPARTMENT = "deleteOrganizationDepartment",
  CREATE_ASSIGNMENT = "createOrganizationAssignment",
  CREATE_CPD_CATEGORY = "createOrganizationCpdCategory",
  UPDATE_CPD_CATEGORY = "updateOrganizationCpdCategory",
}
