export enum OrganizationDashboardMessageCode {
  MEMBER_ADDED = "MEMBER_ADDED",
  REQUIRED_ID = "RequiredFieldId",
  MEMBER_UPDATED = "MEMBER_UPDATED",
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_CREATED = "CATEGORY_CREATED",
  DEPARTMENT_CREATED = "DEPARTMENT_CREATED",
  DEPARTMENT_DELETED = "DEPARTMENT_DELETED",
  DEPARTMENT_UPDATED = "DEPARTMENT_UPDATED",
  ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  TARGET_ROLE_FOUND = "TARGET_ROLE_REQUIRED",
  DEPARTMENT_REQUIRED = "DEPARTMENT_REQUIRED",
  ACCESS_DENIED = "ORGANIZATION_ACCESS_DENIED",
  DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND",
  ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND",
  CATEGORY_EXIST = "CPD_CATEGORY_ALREADY_EXISTS",
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  SETTINGS_UPDATED = "ORGANIZATION_SETTINGS_UPDATED",
  MEMBER_REQUIRED_FOR_ASSIGNMENT = "MEMBER_REQUIRED_FOR_ASSIGNMENT",
}

export enum OrgRangeEnum {
  CUSTOM = "CUSTOM",
  CURRENT_YEAR = "CURRENT_YEAR",
  LAST_QUARTER = "LAST_QUARTER",
}
