export enum AssociationGqlObjectNames {
  ASSOCIATION = "Association",
  ASSOCIATION_GROUP = "AssociationGroup",
  ASSOCIATION_MEMBER = "AssociationMember",
  ASSOCIATION_SETTINGS = "AssociationSettings",
  ASSOCIATION_PAGE_INFO = "AssociationPageInfo",
  ASSOCIATION_MEMBER_GROUP = "AssociationMemberGroup",
  ASSOCIATION_MEMBER_STATS = "AssociationMemberStats",
  ASSOCIATION_INVITE_RESULT = "AssociationInviteResult",
  ASSOCIATION_ACTION_RESPONSE = "AssociationActionResponse",
  PAGINATED_ASSOCIATION_MEMBERS = "PaginatedAssociationMembers",
  ASSOCIATION_BULK_INVITE_RESULT = "AssociationBulkInviteResult",
  ASSOCIATION_BULK_INVITE_FAILURE = "AssociationBulkInviteFailure",
  ASSOCIATION_REQUIREMENT = "AssociationRequirement",
  ASSOCIATION_REQUIREMENT_TARGET = "AssociationRequirementTarget",
  ASSOCIATION_REQUIREMENT_STATS = "AssociationRequirementStats",
  ASSOCIATION_REQUIREMENT_PROBLEM = "AssociationRequirementProblem",
  ASSOCIATION_REQUIREMENT_CATEGORY = "AssociationRequirementCategory",
  ASSOCIATION_REQUIREMENT_AUDIENCE = "AssociationRequirementAudience",
  PAGINATED_ASSOCIATION_REQUIREMENTS = "PaginatedAssociationRequirements",
  ASSOCIATION_MEMBER_COMPLIANCE = "AssociationMemberCompliance",
  ASSOCIATION_ASSIGNMENT_PROGRESS = "AssociationAssignmentProgress",
  ASSOCIATION_CATEGORY_PROGRESS = "AssociationCategoryProgress",
  ASSOCIATION_COMPLIANCE_SUMMARY = "AssociationComplianceSummary",
  ASSOCIATION_PENDING_REVIEW = "AssociationPendingReview",
  ASSOCIATION_REVIEW_RESULT = "AssociationReviewResult",
}

export enum AssociationGqlInputNames {
  ASSOCIATION_PAGINATION = "AssociationPaginationInput",
  CREATE_ASSOCIATION_GROUP = "CreateAssociationGroupInput",
  UPDATE_ASSOCIATION_GROUP = "UpdateAssociationGroupInput",
  ASSOCIATION_MEMBER_FILTER = "AssociationMemberFilterInput",
  UPDATE_ASSOCIATION_MEMBER = "UpdateAssociationMemberInput",
  INVITE_ASSOCIATION_MEMBER = "InviteAssociationMemberInput",
  CREATE_ASSOCIATION_ACCOUNT = "CreateAssociationAccountInput",
  UPDATE_ASSOCIATION_PROFILE = "UpdateAssociationProfileInput",
  SET_ASSOCIATION_GROUP_ACTIVE = "SetAssociationGroupActiveInput",
  SET_ASSOCIATION_MEMBER_STATUS = "SetAssociationMemberStatusInput",
  RESEND_ASSOCIATION_ACTIVATION = "ResendAssociationActivationInput",
  BULK_INVITE_ASSOCIATION_MEMBERS = "BulkInviteAssociationMembersInput",
  BULK_INVITE_ASSOCIATION_MEMBER_ROW = "BulkInviteAssociationMemberRowInput",
  RESEND_ASSOCIATION_MEMBER_INVITATION = "ResendAssociationMemberInvitationInput",
  ASSOCIATION_REQUIREMENT_FILTER = "AssociationRequirementFilterInput",
  ASSOCIATION_REQUIREMENT_CATEGORY = "AssociationRequirementCategoryInput",
  CREATE_ASSOCIATION_REQUIREMENT_DRAFT = "CreateAssociationRequirementDraftInput",
  UPDATE_ASSOCIATION_REQUIREMENT_DETAILS = "UpdateAssociationRequirementDetailsInput",
  UPDATE_ASSOCIATION_REQUIREMENT_CATEGORIES = "UpdateAssociationRequirementCategoriesInput",
  UPDATE_ASSOCIATION_REQUIREMENT_EVIDENCE_RULES = "UpdateAssociationRequirementEvidenceRulesInput",
  UPDATE_ASSOCIATION_REQUIREMENT_REPORTING_RULES = "UpdateAssociationRequirementReportingRulesInput",
  UPDATE_ASSOCIATION_REQUIREMENT_AUDIENCE = "UpdateAssociationRequirementAudienceInput",
  ASSOCIATION_REQUIREMENT_ID = "AssociationRequirementIdInput",
  ASSOCIATION_COMPLIANCE_FILTER = "AssociationComplianceFilterInput",
  REVIEW_ASSOCIATION_LEARNING_ACTIVITY = "ReviewAssociationLearningActivityInput",
}

export enum AssociationGqlQueryNames {
  GROUPS = "associationGroups",
  PROFILE = "associationProfile",
  MEMBERS = "associationMembers",
  MEMBER_STATS = "associationMemberStats",
  REQUIREMENTS = "associationRequirements",
  REQUIREMENT = "associationRequirement",
  MEMBER_COMPLIANCE = "associationMemberCompliance",
  MEMBER_COMPLIANCE_LIST = "associationMemberComplianceList",
  PENDING_REVIEWS = "associationPendingReviews",
  REQUIREMENT_STATS = "associationRequirementStats",
}

export enum AssociationGqlMutationNames {
  CREATE_GROUP = "createAssociationGroup",
  UPDATE_GROUP = "updateAssociationGroup",
  INVITE_MEMBER = "inviteAssociationMember",
  UPDATE_MEMBER = "updateAssociationMember",
  UPDATE_PROFILE = "updateAssociationProfile",
  CREATE_ACCOUNT = "createAssociationAccount",
  SET_GROUP_ACTIVE = "setAssociationGroupActive",
  SET_MEMBER_STATUS = "setAssociationMemberStatus",
  RESEND_ACTIVATION = "resendAssociationActivation",
  BULK_INVITE_MEMBERS = "bulkInviteAssociationMembers",
  RESEND_MEMBER_INVITATION = "resendAssociationMemberInvitation",
  CREATE_REQUIREMENT_DRAFT = "createAssociationRequirementDraft",
  UPDATE_REQUIREMENT_DETAILS = "updateAssociationRequirementDetails",
  UPDATE_REQUIREMENT_CATEGORIES = "updateAssociationRequirementCategories",
  UPDATE_REQUIREMENT_EVIDENCE_RULES = "updateAssociationRequirementEvidenceRules",
  UPDATE_REQUIREMENT_REPORTING_RULES = "updateAssociationRequirementReportingRules",
  UPDATE_REQUIREMENT_AUDIENCE = "updateAssociationRequirementAudience",
  PUBLISH_REQUIREMENT = "publishAssociationRequirement",
  ARCHIVE_REQUIREMENT = "archiveAssociationRequirement",
  REVIEW_LEARNING_ACTIVITY = "reviewAssociationLearningActivity",
  RECOMPUTE_COMPLIANCE = "recomputeAssociationCompliance",
}
