export enum AssociationMessageCode {
  ACCESS_DENIED = "ASSOCIATION_ACCESS_DENIED",
  ACCOUNT_CREATED = "ASSOCIATION_ACCOUNT_CREATED",
  ASSOCIATION_NOT_FOUND = "ASSOCIATION_NOT_FOUND",
  PROFILE_UPDATED = "ASSOCIATION_PROFILE_UPDATED",
  ASSOCIATION_ID_REQUIRED = "ASSOCIATION_ID_REQUIRED",
  ALREADY_ACTIVATED = "ASSOCIATION_ALREADY_ACTIVATED",
  EMAIL_ALREADY_IN_USE = "ASSOCIATION_EMAIL_ALREADY_IN_USE",
  ACTIVATION_EMAIL_SENT = "ASSOCIATION_ACTIVATION_EMAIL_SENT",
  ACTIVATION_EMAIL_NOT_SENT = "ASSOCIATION_ACTIVATION_EMAIL_NOT_SENT",
  ACTIVATION_RESEND_TOO_SOON = "ASSOCIATION_ACTIVATION_RESEND_TOO_SOON",
}
